<a href="https://colab.research.google.com/github/purnasaikrishna06-create/CODSOFT_TASKSNO/blob/main/task_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv('/content/Employe_Performance_dataset.csv')

#  Inspect its structure

In [ ]:
df.head()

,ID,Name,Age,Gender,Department,Salary,Joining Date,Performance Score,Experience,Status,Location,Session
0,1,Cory Escobar,48,Female,HR,5641,2015-05-03,2.0,16,Active,New York,Night
1,2,Timothy Sanchez,25,Other,Sales,4249,2020-11-09,2.0,11,Inactive,Los Angeles,Evening
2,3,Chad Nichols,57,Other,Sales,3058,2019-02-12,NaN,1,Inactive,New York,Morning
3,4,Christine Williams,58,Female,IT,5895,2017-09-08,2.0,13,Inactive,Los Angeles,Evening
4,5,Amber Harris,35,Other,IT,4317,2020-02-15,5.0,16,Inactive,New York,Evening

In [ ]:
df.tail()

,ID,Name,Age,Gender,Department,Salary,Joining Date,Performance Score,Experience,Status,Location,Session
995,996,Pamela Reeves,49,Female,Sales,7652,2024-06-23,4.0,3,Active,Los Angeles,Evening
996,997,Todd Johnson,29,Female,Sales,6754,2018-07-20,NaN,12,Inactive,New York,Morning
997,998,Michael Sanchez,18,Male,Sales,5278,2023-07-05,5.0,3,Active,New York,Morning
998,999,Ashley Taylor,51,Female,IT,5437,2022-02-18,4.0,9,Inactive,Los Angeles,Evening
999,1000,Shawn Scott,45,Male,IT,7364,2022-07-31,2.0,4,Active,New York,Morning

In [ ]:
df.shape

(1000, 12)

In [ ]:
df.dtypes.value_counts()

object     7
int64      4
float64    1
Name: count, dtype: int64

In [ ]:
df.isnull().sum()

ID                     0
Name                   0
Age                    0
Gender                 0
Department             0
Salary                 0
Joining Date           0
Performance Score    498
Experience             0
Status                 0
Location               0
Session                0
dtype: int64

In [ ]:
df.columns

Index(['ID', 'Name', 'Age', 'Gender', 'Department', 'Salary', 'Joining Date',
       'Performance Score', 'Experience', 'Status', 'Location', 'Session'],
      dtype='object')

In [ ]:
df.describe()

                ID          Age       Salary  Performance Score   Experience
count  1000.000000  1000.000000  1000.000000         502.000000  1000.000000
mean    500.500000    40.782000  5917.374000           2.910359    10.120000
std     288.819436    14.124871  2299.418003           1.424736     5.713689
min       1.000000    18.000000  2015.000000           1.000000     1.000000
25%     250.750000    28.000000  3829.750000           2.000000     5.000000
50%     500.500000    40.000000  5889.000000           3.000000    10.000000
75%     750.250000    52.000000  7903.250000           4.000000    15.000000
max    1000.000000    65.000000  9993.000000           5.000000    20.000000