<a href="https://colab.research.google.com/github/purnasaikrishna06-create/CODSOFT_TASKSNO/blob/main/task_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv('/content/Employe_Performance_dataset.csv')

Inspect its structure

In [ ]:
df.head()

,ID,Name,Age,Gender,Department,Salary,Joining Date,Performance Score,Experience,Status,Location,Session
0,1,Cory Escobar,48,Female,HR,5641,2015-05-03,2.0,16,Active,New York,Night
1,2,Timothy Sanchez,25,Other,Sales,4249,2020-11-09,2.0,11,Inactive,Los Angeles,Evening
2,3,Chad Nichols,57,Other,Sales,3058,2019-02-12,NaN,1,Inactive,New York,Morning
3,4,Christine Williams,58,Female,IT,5895,2017-09-08,2.0,13,Inactive,Los Angeles,Evening
4,5,Amber Harris,35,Other,IT,4317,2020-02-15,5.0,16,Inactive,New York,Evening

In [ ]:
df.tail()

,ID,Name,Age,Gender,Department,Salary,Joining Date,Performance Score,Experience,Status,Location,Session
995,996,Pamela Reeves,49,Female,Sales,7652,2024-06-23,4.0,3,Active,Los Angeles,Evening
996,997,Todd Johnson,29,Female,Sales,6754,2018-07-20,NaN,12,Inactive,New York,Morning
997,998,Michael Sanchez,18,Male,Sales,5278,2023-07-05,5.0,3,Active,New York,Morning
998,999,Ashley Taylor,51,Female,IT,5437,2022-02-18,4.0,9,Inactive,Los Angeles,Evening
999,1000,Shawn Scott,45,Male,IT,7364,2022-07-31,2.0,4,Active,New York,Morning

In [ ]:
df.shape

(1000, 12)

In [ ]:
df.dtypes.value_counts()

object     7
int64      4
float64    1
Name: count, dtype: int64

In [ ]:
df.columns

Index(['ID', 'Name', 'Age', 'Gender', 'Department', 'Salary', 'Joining Date',
       'Performance Score', 'Experience', 'Status', 'Location', 'Session'],
      dtype='object')

In [ ]:
df.describe()

                ID          Age       Salary  Performance Score   Experience
count  1000.000000  1000.000000  1000.000000         502.000000  1000.000000
mean    500.500000    40.782000  5917.374000           2.910359    10.120000
std     288.819436    14.124871  2299.418003           1.424736     5.713689
min       1.000000    18.000000  2015.000000           1.000000     1.000000
25%     250.750000    28.000000  3829.750000           2.000000     5.000000
50%     500.500000    40.000000  5889.000000           3.000000    10.000000
75%     750.250000    52.000000  7903.250000           4.000000    15.000000
max    1000.000000    65.000000  9993.000000           5.000000    20.000000

2 ~ Missing values

In [ ]:
df.isnull()

,ID,Name,Age,Gender,Department,Salary,Joining Date,Performance Score,Experience,Status,Location,Session
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,True,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,True,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum()

ID                     0
Name                   0
Age                    0
Gender                 0
Department             0
Salary                 0
Joining Date           0
Performance Score    498
Experience             0
Status                 0
Location               0
Session                0
dtype: int64

 Duplicate records

In [ ]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [ ]:
df.duplicated().sum()

np.int64(0)

Inconsistent

In [ ]:
for col in df.select_dtypes(include='object').columns:
  print(col,"->",df[col].unique())

Name -> ['Cory Escobar' 'Timothy Sanchez' 'Chad Nichols' 'Christine Williams'
 'Amber Harris' 'Ashley Howe' 'David Olson' 'Amanda Baker' 'Jeremy Wright'
 'Brian Faulkner' 'Nicole Bell' 'Rodney Richardson' 'Joshua Robinson'
 'Benjamin Callahan' 'Matthew Collins MD' 'Gary Cooley' 'Jonathan Perez'
 'Jacqueline Randall' 'Nancy Stephens' 'Victoria Fox' 'Heather Jones'
 'Stacie Porter' 'Bryce Carter' 'Marissa Stewart' 'Tracy Carlson'
 'Tara Blackwell' 'Austin Long' 'Jordan Warren' 'Vickie Campbell'
 'Rachel Ramsey' 'Brandi Smith' 'Jacqueline Becker' 'Trevor Duncan'
 'Mr. Brian Nelson' 'Lisa Fry' 'Kevin Watts' 'Jacqueline Moore'
 'Lawrence Rose' 'Jordan Scott' 'Lisa Wagner' 'Ricky Keith'
 'Charles Mccall' 'April Ponce' 'Cindy Nichols' 'Daniel Aguirre'
 'Dr. Monica Hanna PhD' 'Alicia Scott' 'Jake Johnson' 'Jamie Wood'
 'Valerie Guerrero' 'Jamie Gregory' 'Jesse Vincent' 'Steve Salinas'
 'Taylor Griffin' 'Kim Smith' 'Jonathon Adams' 'Jeremy Conway'
 'Johnathan Obrien' 'Erik Moss' 'Melinda Tyler' 'Andrew Shannon'
 'Carmen Taylor' 'Joseph Anderson' 'Katherine Clark' 'Mary Miller'
 'Sarah Harrell' 'Kelli Lopez' 'Denise Smith' 'Alyssa Taylor'
 'Erica James' 'Daniel Hamilton' 'Tiffany Alexander' 'Jennifer Carter'
 'Amanda Rodgers' 'Francisco Jones' 'Cameron Butler' 'Victor Nelson'
 'Kathy Thompson' 'Michele Schmidt' 'Mary Singh' 'Julia Stanley'
 'Kevin Price' 'Jamie Wright' 'Elaine Payne' 'Justin Rodriguez'
 'Chase Taylor' 'Dustin Allen' 'Lori Bowen' 'Jessica Sanders' 'Lauren Lee'
 'Kyle Schwartz' 'Bruce Campbell' 'Peter Moore' 'Elizabeth Gallagher'
 'Michael Garcia' 'Jeff Wilson' 'Holly Gaines' 'Matthew Fields'
 'Kathleen Thomas' 'Thomas Hamilton' 'Bryan Navarro' 'Jennifer Hansen'
 'James Saunders' 'Jose Henson' 'Isaiah Sanders DDS' 'Katelyn Chavez'
 'Nancy Robinson' 'Sandra Allen' 'Mrs. Robin Mccarthy PhD' 'Catherine Ray'
 'James Johnson' 'Sarah Barrera' 'Luke Mcpherson' 'Michael Moore'
 'Donna Manning' 'John Lloyd' 'Sean Owens' 'Gregory Robinson'
 'Tara Hudson' 'Heidi Franklin' 'David Hampton' 'Jacob Gonzalez'
 'Kenneth Jensen' 'Amber Pittman' 'William Hall' 'Michael Wilson'
 'Vanessa Gray' 'Ashley Williams' 'Shawn Marshall' 'Derrick Woods'
 'Lisa Levy' 'Amy Patel' 'Gregory Villegas' 'Arthur Tyler'
 'Jonathan Schneider' 'Donna Fox' 'Rebecca Pitts' 'Annette Peterson'
 'Mr. James Moore' 'William Hernandez' 'Kevin Ruiz' 'Matthew Gutierrez'
 'Kelly Phillips' 'Dana Potter' 'Kimberly Murphy' 'Jessica Hernandez'
 'Rachel Allen' 'Mr. Brandon Gonzales' 'Matthew Perkins' 'Robert Adkins'
 'Anthony Moran' 'Julie Wilson' 'Mark Morris' 'Charles Marsh'
 'Larry Johnson' 'Raymond Johnson' 'Pamela Pierce' 'Debra Smith'
 'Erin Harrison' 'Thomas Gordon' 'Cindy Torres' 'Mario Newman'
 'Emily Hughes' 'Emily Fisher' 'Sheryl Everett DDS' 'Caleb Coffey'
 'Brianna Murray' 'Amy Bell' 'Tonya Estrada' 'George Bowers'
 'Tyler Figueroa' 'Roger Pugh' 'Paul Ross' 'Steven Green' 'Amanda Walters'
 'Cody Sanchez' 'Sherri Hess' 'David Buchanan' 'Daniel Hoffman'
 'Kathryn Choi' 'Sharon Patterson' 'Brooke Norris' 'Linda Wilson'
 'Nathaniel Miller' 'Michael Edwards' 'Jane Gardner' 'Anthony Lucas'
 'Robert Colon' 'Patrick Williams' 'Tiffany Hopkins' 'Miguel Finley'
 'John Sullivan' 'Albert Stevens' 'Dean Barnes' 'Eric York'
 'Breanna Ballard' 'Joshua Booker' 'Mary King' 'Jennifer Brown DVM'
 'Gregory Cohen' 'Mr. James Johnson' 'Elizabeth Jordan' 'Robert Carey'
 'Randy Pace' 'Brian Herrera' 'Julie Hayden' 'Mario Jackson'
 'Dawn Flowers' 'Darrell Burns' 'Mr. Jason Jones' 'Joseph Li'
 'Christopher Barrera' 'Tyler Carroll' 'Rachel Mcdonald' 'Dawn Nelson'
 'Sara Jones' 'Alison Anderson' 'Jeffery Hurley' 'Melissa Flores'
 'Erika Schneider' 'Steven Salinas' 'Kenneth Taylor' 'Jennifer Hartman'
 'Cheryl Potter' 'Lori Rodriguez' 'Brian White' 'Ashley Robbins'
 'Mary Mcguire' 'Christie Warren' 'Monica Henderson' 'Connie Lucas'
 'William Harris' 'Michelle Mendez' 'Richard Mendez' 'Stuart Rodriguez'
 'Curtis Diaz' 'Joan Trevino' 'Gregory Pollard' 'Lori Petty'
 'Christina Gutierrez' 'Ashley Kim' 'Jennifer Wilson' 'Scott Russell'
 'Evan Blackburn' 'Justin Hampton' 'Marie Reese' 'Sheila Gordon'
 'Jessica Davis' 'Tyler Carter' 'David Burke' 'Joshua Bullock'
 'Gabriel Peters' 'Christine Duran' 'Nancy Mendez' 'Susan Fisher'
 'Meghan Burgess' 'Jeffery Jackson' 'David Tran' 'Karina Harris'
 'Bradley Gibbs' 'Stephen Mitchell' 'Gabriel Warren' 'James Hines'
 'Gabriela Wilson' 'Kara Wilson' 'John Butler' 'Jared Villanueva'
 'Mary Hammond' 'Margaret Mayo' 'Ray Smith' 'Derek Morris'
 'Carrie Martinez' 'Thomas Spence' 'Carrie Sloan'
 'Mrs. Kimberly Woodard MD' 'Harry Alexander' 'David Cox' 'Sheryl Gray'
 'Michael Bishop' 'Dalton Moore' 'Caroline Bell' 'Vanessa Shelton'
 'Scott White' 'Richard Smith' 'Daniel Rodriguez' 'Mr. Kevin Bradley'
 'Judith Evans' 'Michele Roman' 'Barry Mckenzie' 'Sara Stokes'
 'Rebecca Bailey' 'Rachel Sosa' 'Amy Hubbard' 'Gary Grant'
 'Kimberly Smith' 'Jennifer Nichols' 'Rachel Robinson' 'Brandon Atkinson'
 'Dawn Mclaughlin' 'Terry Smith' 'Alejandro Bennett' 'Patricia Williams'
 'Jose Sharp' 'Sarah Stark' 'Mark Thomas' 'Alexander Johnson'
 'Henry Harmon' 'Nancy Jackson' 'Taylor Walters' 'Abigail Rodriguez'
 'Dr. Susan Cook' 'John Jensen' 'Sean Barrett' 'Kenneth Brown'
 'Samantha Clark DDS' 'Cynthia Cox' 'Jamie Gonzalez' 'Joseph Thomas'
 'Brent Montes' 'Elizabeth Dudley' 'Alexa Romero' 'Jerry Smith'
 'James Smith' 'Anthony Lam' 'Tom Diaz' 'Vanessa Gill' 'Robert Hensley'
 'Matthew Guerrero' 'Jennifer Vargas' 'Taylor Lopez' 'Juan Dean'
 'Karen Hayden' 'Heather Anderson' 'Austin Reyes' 'Melissa Fisher'
 'Danny Allen' 'Jose Costa' 'Michelle Brennan' 'Amanda Conner'
 'Christopher Jones' 'Tyrone Juarez' 'Chad Nelson' 'Zachary Gutierrez'
 'Mark Mcbride' 'Debra Mcdonald' 'Luis Sanchez' 'David Durham'
 'Claire Randall' 'Rebecca Stewart' 'Ryan Cox' 'Andrew Fletcher'
 'Nicole Sanchez' 'Paul Walters' 'Melissa Johnson' 'Karen Ramos'
 'Laura Castillo' 'James Anderson' 'Andre Hall' 'Scott Hernandez'
 'Wendy Lee' 'Tony Ellison' 'Samuel Irwin' 'Mr. Timothy Mitchell DDS'
 'Linda Wall' 'Mrs. Jacqueline Woodard MD' 'Johnny Cook'
 'Miss Barbara Short' 'Adam Lane' 'Natasha Spencer' 'Dawn Sanchez'
 'Robert Sims' 'Allison Carroll' 'Dominic Gray' 'Eric Hill'
 'Anthony Baldwin' 'Jeffrey Nguyen' 'Jonathon Mclaughlin' 'John Anderson'
 'Amy Harvey' 'Dustin Le' 'Kenneth Davis' 'David Marshall' 'Kelly Norton'
 'Wendy Taylor' 'Monica Baldwin' 'Joseph Martin' 'Omar Martinez'
 'Corey Smith' 'Maria Bowman' 'Sandra Gill' 'Chloe Newman'
 'Natalie Chavez DDS' 'Marilyn Baker' 'Robert Oliver' 'Mary Mcmillan'
 'Carolyn Arnold' 'Sarah Ruiz' 'Christina Lewis' 'Bradley Hernandez'
 'Allen Miller' 'Nathan Flores' 'Briana Martin' 'David Clark'
 'Leroy Jones' 'Heather Scott' 'Vanessa Mendoza' 'George Weaver'
 'Doris Cooper' 'Bruce Anderson' 'Kimberly Reed' 'Tammy Allison'
 'Dale Mejia' 'Jacob Kelley' 'Matthew Hampton' 'Brandon Smith'
 'Cynthia Hall' 'Angel Fuller' 'Sonia Davis' 'Terry Gomez' 'Travis Brown'
 'Dylan Dixon' 'James Newton' 'Antonio Shields' 'Tricia Coleman'
 'Ryan Munoz' 'Patricia Scott' 'Ashley Gonzales' 'Vicki Carter'
 'Matthew Turner' 'James Melton' 'Kayla Gregory' 'Bryan Medina'
 'Cameron Harris' 'Richard Rich' 'Jason Robertson' 'Philip Huff'
 'Kristie Nelson' 'Mrs. Lisa Suarez' 'Nicholas Wilson' 'Catherine Jordan'
 'Michele Ruiz' 'Kimberly Sparks' 'Joseph Oconnor' 'Joseph Armstrong'
 'Stephen Little' 'Melissa Clark' 'Michelle Robertson' 'Nathan Rodriguez'
 'Marissa Hunt' 'Steve Adams' 'Crystal Reyes' 'Lindsey Hall' 'Jay Clark'
 'Michael Reeves' 'Nicole Baxter' 'Cheryl Davila' 'Emma Pratt'
 'Jennifer Nelson' 'William Garrett' 'Jose Allen' 'Anne Hernandez'
 'Christopher Stevens' 'Alex Gordon' 'Justin Thornton' 'Jeremy Perez'
 'Janet Carpenter' 'Kimberly Brown' 'Luis Shaw' 'Amanda Smith'
 'Stephanie Jackson' 'Matthew Thomas' 'Faith Morris' 'David Potter'
 'Kimberly Lang' 'Alicia Malone' 'Gregory Sparks' 'Mary Arias'
 'Jeffrey Robles' 'Jay Scott' 'Brandon Flores' 'Donna King'
 'Curtis Barrett' 'Jason Hayden' 'Patricia Washington' 'Chelsea Owens'
 'Kayla Garcia' 'Lisa Torres' 'Madison Smith' 'Molly Choi'
 'Kristy Phillips' 'Dr. Jacob Castaneda DVM' 'Dr. Thomas Brown'
 'Michael Torres' 'Scott Fleming' 'Patrick Martin' 'Brittany Martinez'
 'Lori Thomas' 'Paul Mccullough' 'Bruce Rodriguez' 'Kristi Stevens'
 'Christina Hayes' 'Dawn Choi' 'Zachary Bowen' 'Crystal Lee'
 'Dr. Justin Vega' 'Bradley Riley' 'George Mcpherson' 'Erica Garcia'
 'Christopher Black' 'Charles Smith' 'Ellen Wright' 'Ryan Hess'
 'Miss Alyssa Perez DDS' 'Taylor Williamson' 'Megan Sullivan'
 'Christina Lowe' 'Anthony Sanchez DVM' 'Kyle Strong' 'Omar Thomas'
 'Angela Jimenez' 'Rebecca Stone' 'Kyle Smith' 'Gwendolyn Ray'
 'Stephen Wilcox' 'Ashley Barber' 'Brittany Holt' 'Amber Rodriguez'
 'Anne Roberts' 'Katie Vega' 'Gabriel Weber' 'Jeffrey Williamson'
 'Jason Juarez' 'Toni Hall' 'Ryan Ramos' 'Thomas Stuart' 'Joseph Adams'
 'Kimberly Burke' 'Brandon Church' 'Jonathan Reed' 'Julie Turner'
 'Joseph Vargas' 'Michael Parker' 'Erin Cunningham' 'Elizabeth Watson'
 'Tara Mccoy' 'Louis Larsen' 'Tara Waller' 'Morgan Thompson'
 'Jason Greene' 'Patricia Terry' 'Melissa Erickson' 'Amanda Griffith'
 'Leslie Walker' 'Johnny Dalton' 'Crystal Kidd' 'Kristina Phillips'
 'Michaela Rivera' 'Tammy Mcpherson' 'Carrie Thomas' 'Kimberly Davis'
 'Pamela Levine' 'Beverly Logan' 'Pamela Ellison' 'Kathleen Ross'
 'Erica Jones' 'Adam Thomas' 'Courtney Lucas' 'Kimberly Montgomery'
 'Paul Smith' 'Tamara Harding' 'Suzanne Miller' 'Laura Harvey'
 'Patrick Rodriguez' 'Sabrina Davis' 'Eric Smith' 'Chad Kennedy'
 'Denise Lindsey' 'Dawn Fuller MD' 'Mark Santiago' 'Jennifer Stewart'
 'Sara Harris' 'Nicholas Anderson' 'Robin Williams' 'Angela Bell'
 'Alexander Mitchell' 'Leslie Harmon' 'Krystal Rice' 'Mr. Gary Ramos'
 'Meghan Beck' 'Nancy Vincent' 'Jonathan Rangel' 'Laura Smith'
 'Amber Mason' 'Michelle Smith' 'Megan Barry' 'Kathy Clark'
 'Brenda Torres' 'James Rose' 'Stephen Weber' 'Jason Hess'
 'Connie Collins' 'Melissa Evans' 'Thomas Martinez' 'Erin Phillips'
 'Stephanie Lopez' 'Christopher Knapp' 'Shelly Russo' 'Kimberly Galvan'
 'Renee Burnett' 'Kerry Simon' 'Alfred Barr' 'Kelsey Hines'
 'Kimberly Dunlap' 'David Pena' 'Sarah Castro' 'Tiffany Richardson'
 'Terry Burch' 'Jason Davis' 'Henry Bennett' 'John Rodriguez'
 'Joseph Smith' 'Anthony Miller' 'Jennifer Clark' 'Douglas Martin'
 'Brenda Carter' 'Terri Foster' 'Brenda Lang' 'Melissa Vega'
 'Taylor Thompson' 'Tina Welch' 'Heather Arias' 'Ralph Newman'
 'Stacy Bell' 'Tyler Miller' 'Valerie Lee' 'Jimmy Wade' 'Carlos Mcmillan'
 'Laurie Mata' 'Brianna Phelps' 'Heather Henry' 'Rebecca Avery'
 'Anthony Blankenship' 'Alice Martin' 'Phillip Nelson' 'Emily Martin'
 'Monica Blake' 'Rebecca Carter' 'Jason Warren' 'Julian Maxwell'
 'Mrs. Kimberly Day MD' 'Rachel Roman' 'Elizabeth Johnston'
 'Sabrina Norris' 'Brandi Harvey' 'Hayden Parsons' 'Gregory Marshall'
 'Eric Bailey' 'Dawn Coleman' 'Alex Jones' 'Bobby Tanner'
 'Jeffrey Stephens' 'Brenda Mendoza' 'John Adkins' 'James Diaz'
 'Leslie Velez' 'Michael Lee' 'Lindsey Davis' 'Sara Brewer' 'Seth Brown'
 'Stanley White' 'Mrs. Theresa Wilson' 'John Freeman' 'Charles Nichols'
 'Cory Roth' 'Michelle Durham' 'Manuel Lewis' 'Jeremy Garcia'
 'Christy Jordan' 'Colleen Jones' 'Zachary Brown' 'Jill Stanton'
 'Kristen Jackson' 'Jillian Ramos' 'Angel Henry' 'Brandon Martin'
 'Natalie Byrd' 'Samuel Rivera' 'Dr. Danny Mccann' 'Jim Scott'
 'Molly Harris' 'Edward Smith' 'Jessica Lopez' 'Cynthia Melton'
 'John Smith' 'Carl Armstrong' 'Ashley Garcia' 'David Pierce'
 'Jerry Thompson' 'Lisa Ramirez' 'Rhonda Salinas' 'Cheryl Chambers'
 'Mr. Micheal Henry' 'Raymond Nelson' 'Angela Roberts' 'Megan Lamb'
 'Brian Owens' 'Jacob Woods' 'Ellen Barker' 'Dana Garcia' 'Howard Key'
 'Melissa Wallace' 'Monique Davis' 'Mary Martinez' 'Jeff Johnson'
 'Douglas Ramirez' 'Amy Miller' 'Patrick Evans' 'Shannon Jackson'
 'Kelly Rios' 'Jill Buchanan' 'Keith Johnson' 'Gregory Smith'
 'Joseph Klein' 'David Gregory' 'Tammy Dixon' 'Linda Hawkins'
 'Deborah Sanchez' 'Melissa Carey' 'Corey Johnson' 'Jay Evans'
 'Kevin Green' 'Rebecca Padilla' 'Dave Romero' 'David Mills'
 'William Alexander' 'Mr. John Hill II' 'John Foster' 'Christy Berry'
 'Jason Ortiz' 'Timothy Guzman' 'Manuel Ramirez' 'Erik Rodriguez'
 'Jo Richards' 'Veronica Bennett' 'Zoe Camacho' 'Jennifer Cruz'
 'William Garza' 'Matthew Anderson' 'David Powell IV' 'Lynn Franco'
 'Kelly Sutton' 'Sheri Cortez' 'Stanley Baker' 'James James'
 'Mr. Harry Allen' 'Matthew Roberts' 'Gary Lee' 'Taylor Dean'
 'Madeline Contreras' 'Terri Ross' 'Darrell Wall' 'Roberta Haas'
 'Steve Smith' 'William Davis' 'Paige Hayes' 'Julie Baird' 'Isaac Shannon'
 'Daniel Lee' 'Willie Miller' 'Bryan Brown' 'Penny Jennings'
 'Christopher Swanson' 'Emily Price' 'Rebecca Gonzalez' 'Danielle Garza'
 'David Nelson' 'Brian Phillips' 'Anita Jones' 'Sheila Moore'
 'Alex Thompson' 'Danielle Gomez' 'Alyssa Harris' 'Steve Morton'
 'David Williams' 'Lauren Williams' 'Carrie Butler' 'Matthew Hernandez'
 'Lauren Richardson' 'Olivia Butler' 'Carrie Clark' 'Elizabeth Wolf'
 'Joanne Griffin' 'Jacob Shannon' 'Melanie Casey' 'Lori Gray'
 'Ann Mcdonald' 'Jesse Wilson' 'Cynthia Vasquez' 'Lawrence Smith'
 'Jacob Aguilar' 'Gerald Sharp' 'Terri Richards' 'Elizabeth Vega'
 'Jeremy Cooper' 'Matthew Bonilla' 'Eric Montgomery' 'Susan Gonzalez'
 'Jesse Miller' 'Mr. Dustin Cross' 'Dr. Pamela Key' 'Jennifer Ward'
 'Philip Henderson' 'Rachael Benson' 'Donald Warner' 'Wayne Schneider'
 'Amber Ward' 'Karen Washington' 'Shawn Wells' 'Michelle Jackson'
 'Jesse Mendoza' 'Tracy Powers' 'Sarah Sanders' 'Maria Franklin'
 'Melanie Andersen' 'Michael Snyder' 'Kimberly Morris' 'Daniel Williamson'
 'Jared Webb' 'Susan Davis' 'Michelle Wolfe' 'Keith Smith'
 'Jonathan Rivera' 'Bryan Walsh' 'William Best' 'Anne Estes'
 'Jeffrey Morton' 'Jacqueline Evans' 'Tammy Smith' 'Sara King'
 'Robert Goodman' 'Gerald Cooke' 'Natasha Harris' 'Darryl Nolan'
 'Edward Wilkerson' 'Frank Gomez' 'Dr. Shawn Miranda' 'Geoffrey Roberts'
 'Elizabeth Kramer' 'Robert Williams' 'Mr. Ryan Beck' 'Amy Heath'
 'Zachary Cox' 'Nicholas Guerra' 'Sarah Fletcher' 'Katelyn Jacobson'
 'Jenna Marquez' 'Jennifer Smith' 'Daniel Duke' 'Dana Payne'
 'Miss Jessica Jones' 'Jessica Garcia' 'Rachel Jones' 'Brent Mendoza'
 'Daniel Malone' 'Nicholas Rodriguez' 'Jerry Lopez' 'Nicole Cook'
 'Anthony Ferguson' 'Kimberly Miller' 'Katherine Wong' 'John Becker'
 'Nicole Smith' 'Megan Castillo' 'Ashley Alvarado' 'Sarah Thomas'
 'Mckenzie Moore' 'Ryan James' 'Jaclyn Collins' 'Jay Atkinson'
 'Whitney Chambers' 'Dawn Gonzales' 'Christine Hooper' 'Joel Anthony'
 'Jodi Graves' 'Vicki Taylor' 'Johnathan Donaldson' 'Monica Parker'
 'Chelsea Hill' 'Lance Davis' 'Ruth Randall' 'Patricia Lee'
 'Tyrone Elliott' 'Laura Montgomery' 'Tiffany Jordan' 'Richard Pearson'
 'John Rogers' 'Andrea Bond' 'Christina Henry' 'Leslie Mason'
 'Daniel Stanley' 'Bradley Parker' 'Christina Carlson' 'Sara Martinez'
 'Peter Hardy' 'Kimberly Moses' 'Larry Fritz' 'Courtney Lopez'
 'Megan Woods' 'Benjamin Brown' 'Matthew Cole' 'Jose Powell' 'Erin Walker'
 'Tammy Schneider' 'Cheryl Singh' 'Vicki Hicks' 'Rachel Spencer'
 'Joseph Murillo' 'Eric Collins' 'Richard Martin' 'John Thompson'
 'Laura Stewart' 'Jason Reed' 'Christopher Taylor'
 'Nathaniel Castillo DDS' 'Stephanie Rodriguez' 'Ronald Miller'
 'Kristin Cole' 'Jeanette Mcbride' 'Christopher Krause' 'Ryan Vazquez'
 'Justin Turner' 'Gary Mitchell' 'Andrea Odom' 'Joshua Murphy'
 'Raymond Smith' 'Elizabeth Middleton' 'Logan Peterson' 'Tina Ramos'
 'Mary Armstrong' 'Joel Tyler' 'Alex Walker' 'Laura White' 'Kevin Bates'
 'Dustin Carrillo' 'Glenn Alexander' 'Kevin Pearson' 'Carmen Hurley'
 'Ruth Osborne' 'Gregory James' 'Erin Kelley' 'Debra Knox' 'Stacy Rogers'
 'Morgan Coleman' 'Alex Stuart' 'Charlene Nelson' 'Paula Moreno'
 'Matthew Rowe' 'John Jordan' 'April Parsons' 'Edgar Herrera MD'
 'Andres Barnett' 'Elizabeth Miles' 'Nicholas Edwards' 'Michael Mejia'
 'Michael Reed' 'Kelsey Fischer' 'James Mendoza' 'Catherine Kelley'
 'Brett Myers' 'Bryce Anderson' 'Kimberly Ross' 'Crystal Espinoza'
 'Jeffrey Johnson' 'Emily Anderson' 'Stephen Ponce' 'David Moody'
 'Jeffrey Hall' 'Regina Ferguson' 'Melissa Bradley' 'Danielle Brown'
 'Hannah Hickman' 'Shannon Meyer' 'Amy Johnston' 'William Schultz'
 'Ashley Daniels' 'Brandon Bruce' 'Rachel Phillips' 'Pamela Reeves'
 'Todd Johnson' 'Michael Sanchez' 'Ashley Taylor' 'Shawn Scott']
Gender -> ['Female' 'Other' 'Male']
Department -> ['HR' 'Sales' 'IT']
Joining Date -> ['2015-05-03' '2020-11-09' '2019-02-12' '2017-09-08' '2020-02-15'
 '2016-06-24' '2023-05-11' '2015-04-01' '2024-02-07' '2018-05-26'
 '2015-01-28' '2015-03-14' '2020-06-21' '2019-06-23' '2020-06-01'
 '2017-07-25' '2019-02-19' '2018-05-18' '2017-07-16' '2023-06-07'
 '2018-02-07' '2020-05-04' '2015-12-16' '2021-01-30' '2022-04-09'
 '2020-02-20' '2024-05-01' '2018-07-07' '2019-10-28' '2016-08-18'
 '2020-01-20' '2021-12-16' '2024-06-10' '2017-08-17' '2017-09-26'
 '2019-06-12' '2018-02-25' '2021-04-11' '2016-05-15' '2024-08-12'
 '2024-01-29' '2024-11-10' '2021-10-22' '2014-12-19' '2017-10-03'
 '2020-10-31' '2019-09-03' '2017-02-03' '2023-02-25' '2023-09-21'
 '2015-12-07' '2023-09-17' '2022-03-26' '2019-01-07' '2023-10-11'
 '2020-07-29' '2024-08-11' '2021-04-09' '2021-04-12' '2020-02-08'
 '2023-01-30' '2023-06-02' '2023-02-17' '2019-10-19' '2021-01-01'
 '2021-09-21' '2024-10-31' '2017-10-19' '2020-09-28' '2018-04-08'
 '2019-05-18' '2016-04-06' '2018-03-21' '2023-07-01' '2023-10-20'
 '2015-05-14' '2016-02-23' '2016-05-22' '2019-07-06' '2021-07-28'
 '2020-11-12' '2020-11-02' '2017-06-23' '2020-07-01' '2017-10-04'
 '2015-01-08' '2023-01-07' '2024-08-02' '2020-07-16' '2023-03-16'
 '2023-12-20' '2021-03-13' '2023-02-06' '2018-01-29' '2024-06-08'
 '2017-01-14' '2015-08-07' '2018-09-15' '2017-12-24' '2021-01-23'
 '2020-02-22' '2019-09-16' '2023-03-25' '2021-04-28' '2015-10-06'
 '2017-12-19' '2019-01-05' '2019-04-24' '2017-12-10' '2016-08-20'
 '2021-10-30' '2016-01-29' '2021-03-26' '2021-05-10' '2017-05-10'
 '2016-07-09' '2021-01-16' '2022-01-02' '2024-01-26' '2024-07-06'
 '2020-06-12' '2017-04-21' '2018-03-08' '2022-10-16' '2016-12-25'
 '2015-11-27' '2020-05-03' '2019-01-21' '2019-09-22' '2021-07-07'
 '2020-08-07' '2021-06-26' '2022-01-19' '2023-08-03' '2023-09-29'
 '2017-06-29' '2020-05-17' '2021-08-21' '2020-11-18' '2020-08-15'
 '2024-10-22' '2020-07-17' '2024-04-07' '2019-05-14' '2017-07-07'
 '2018-01-30' '2023-09-23' '2023-07-12' '2020-10-23' '2017-09-28'
 '2018-08-26' '2017-12-31' '2023-11-01' '2018-11-20' '2016-12-03'
 '2015-04-28' '2019-07-31' '2018-04-30' '2024-09-17' '2015-04-20'
 '2017-03-15' '2016-09-15' '2017-11-15' '2024-05-12' '2018-10-21'
 '2023-10-21' '2022-08-10' '2024-12-07' '2020-12-04' '2023-04-14'
 '2022-01-26' '2015-10-10' '2015-10-26' '2019-01-27' '2021-05-29'
 '2016-01-12' '2016-06-04' '2021-05-08' '2015-02-04' '2020-10-24'
 '2024-03-07' '2023-01-17' '2016-12-20' '2014-12-29' '2023-08-26'
 '2023-05-10' '2021-08-07' '2021-11-10' '2019-08-22' '2018-08-29'
 '2021-02-24' '2019-01-18' '2022-06-25' '2020-08-31' '2022-07-12'
 '2021-05-21' '2018-01-01' '2019-08-04' '2018-10-01' '2021-01-12'
 '2022-02-21' '2018-12-16' '2019-02-09' '2017-12-28' '2021-02-05'
 '2024-06-29' '2022-01-11' '2016-07-30' '2022-10-27' '2021-02-02'
 '2015-12-11' '2016-02-01' '2019-10-16' '2017-11-05' '2016-06-14'
 '2018-05-01' '2023-11-23' '2017-03-05' '2020-08-20' '2018-07-30'
 '2023-12-15' '2017-04-27' '2019-02-06' '2020-08-16' '2016-07-11'
 '2015-12-09' '2016-03-26' '2024-07-17' '2022-04-13' '2017-02-15'
 '2022-11-17' '2023-01-11' '2015-05-09' '2018-01-02' '2023-11-10'
 '2021-10-19' '2020-02-19' '2016-02-19' '2024-11-22' '2019-03-24'
 '2021-12-17' '2024-09-21' '2018-11-23' '2015-09-21' '2019-01-10'
 '2015-05-15' '2018-03-18' '2018-04-20' '2020-01-05' '2017-08-23'
 '2022-08-23' '2021-01-24' '2022-10-09' '2019-03-04' '2022-07-29'
 '2015-12-21' '2022-12-13' '2023-11-19' '2018-09-01' '2024-05-28'
 '2016-06-23' '2020-04-04' '2018-12-02' '2023-08-20' '2024-01-07'
 '2021-06-18' '2016-11-20' '2018-01-16' '2019-03-06' '2019-05-15'

3~

In [ ]:
df=df.fillna(method='ffill')

/tmp/ipykernel_6166/1718901248.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df=df.fillna(method='ffill')

In [ ]:
df.isnull().sum()

ID                   0
Name                 0
Age                  0
Gender               0
Department           0
Salary               0
Joining Date         0
Performance Score    0
Experience           0
Status               0
Location             0
Session              0
dtype: int64

In [ ]:
df=df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

In [ ]:
df["Joining Date"]=pd.to_datetime(df["Joining Date"])
print(df.dtypes)

ID                            int64
Name                         object
Age                           int64
Gender                       object
Department                   object
Salary                        int64
Joining Date         datetime64[ns]
Performance Score           float64
Experience                    int64
Status                       object
Location                     object
Session                      object
dtype: object

In [ ]:
df.head()

,ID,Name,Age,Gender,Department,Salary,Joining Date,Performance Score,Experience,Status,Location,Session
0,1,Cory Escobar,48,Female,HR,5641,2015-05-03,2.0,16,Active,New York,Night
1,2,Timothy Sanchez,25,Other,Sales,4249,2020-11-09,2.0,11,Inactive,Los Angeles,Evening
2,3,Chad Nichols,57,Other,Sales,3058,2019-02-12,2.0,1,Inactive,New York,Morning
3,4,Christine Williams,58,Female,IT,5895,2017-09-08,2.0,13,Inactive,Los Angeles,Evening
4,5,Amber Harris,35,Other,IT,4317,2020-02-15,5.0,16,Inactive,New York,Evening

In [ ]:
df.shape

(1000, 12)

In [ ]:
df.dtypes.value_counts()

object            6
int64             4
datetime64[ns]    1
float64           1
Name: count, dtype: int64

In [ ]:
df.describe()

,ID,Age,Salary,Joining Date,Performance Score,Experience
count,1000.000000,1000.000000,1000.000000,1000,1000.000000,1000.000000
mean,500.500000,40.782000,5917.374000,2020-01-04 21:23:02.400000,2.902000,10.120000
min,1.000000,18.000000,2015.000000,2014-12-11 00:00:00,1.000000,1.000000
25%,250.750000,28.000000,3829.750000,2017-08-22 06:00:00,2.000000,5.000000
50%,500.500000,40.000000,5889.000000,2020-03-01 12:00:00,3.000000,10.000000
75%,750.250000,52.000000,7903.250000,2022-05-30 00:00:00,4.000000,15.000000
max,1000.000000,65.000000,9993.000000,2024-12-07 00:00:00,5.000000,20.000000
std,288.819436,14.124871,2299.418003,NaN,1.381414,5.713689

In [ ]:
df.to_csv("Employee_Performance_cleaned.csv",index=False)

In [ ]:
print("Cleaned dataset saved successfully")

Cleaned dataset saved successfully

In [ ]:
from google.colab import files
files.download("Employee_Performance_cleaned.csv")